spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivroprod?createDatabaseIfNotExist=true
    username: root
    password: 12345678

# Para ativar o profile de prod no Intellij é necessário ir nas configs
# e em VM options: -Dspring.profiles.actives=prod ou o perfil que desejar