spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: 12345678
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /api
jwt:
  secret: dc887464-d212-470c-abb7-975f784a2538
  expiration: 99999
